# Generated by Django 5.1.2 on 2025-01-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('uploaded_by_name', models.CharField(max_length=255)),
                ('uploaded_by_id', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('videos', models.ManyToManyField(related_name='playlists', to='staff_panel.video')),
            ],
        ),
    ]
